// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoU-tkBxE7m60IRKbdEMAiUlLKwRyIxfM',
    appId: '1:888183445557:web:d8d6e134fca3e06169b97c',
    messagingSenderId: '888183445557',
    projectId: 'academgora-6be92',
    authDomain: 'academgora-6be92.firebaseapp.com',
    databaseURL: 'https://academgora-6be92-default-rtdb.firebaseio.com',
    storageBucket: 'academgora-6be92.appspot.com',
    measurementId: 'G-CYW83XHCRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIeIwz_NCSO7LNPB_DwOqBEbwIwgjrmDA',
    appId: '1:888183445557:android:c960f5a618587b8869b97c',
    messagingSenderId: '888183445557',
    projectId: 'academgora-6be92',
    databaseURL: 'https://academgora-6be92-default-rtdb.firebaseio.com',
    storageBucket: 'academgora-6be92.appspot.com',
  );
}
